# Generated by Django 5.2 on 2025-05-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=50)),
                ('stu_sno', models.IntegerField()),
                ('stu_contact', models.IntegerField()),
                ('stu_city', models.CharField(max_length=15)),
            ],
        ),
    ]
