# Generated by Django 5.2.1 on 2025-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=50)),
                ('stu_city', models.CharField(max_length=20)),
                ('stu_subject', models.CharField(max_length=20)),
                ('stu_gender', models.CharField(max_length=10)),
                ('stu_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
