# Generated by Django 5.2 on 2025-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=50)),
                ('Stu_email', models.EmailField(max_length=254)),
                ('Stu_dis', models.CharField(max_length=200)),
                ('Stu_dob', models.DateField()),
                ('Stu_edu', models.CharField(max_length=50)),
                ('Stu_gender', models.CharField(max_length=50)),
                ('Stu_image', models.ImageField(upload_to='image/')),
                ('Stu_document', models.FileField(upload_to='file/')),
                ('Stu_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
