# Generated by Django 5.2 on 2025-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar',
            field=models.IntegerField(unique=True),
        ),
    ]
