# Generated by Django 5.2 on 2025-04-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aadhar_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar'),
        ),
    ]
