# Generated by Django 5.2.1 on 2025-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook_image', models.ImageField(upload_to='image/')),
                ('cook_name', models.CharField(max_length=50)),
                ('cook_email', models.EmailField(max_length=254)),
                ('cook_contact', models.IntegerField()),
                ('cook_foods', models.CharField(max_length=50)),
                ('cook_recipes', models.CharField(max_length=50)),
                ('cook_pass', models.IntegerField()),
            ],
        ),
    ]
